### PR TITLE
22 gpu docker

### LINKED ISSUE #22: Run using Docker and CUDA GPU
Need to make it work with a GPU in Docker

Inspiration to achieve that: https://github.com/opensource-spraakherkenning-nl/asrservice

### PR DESCRIPTION
**Pull request by greenw0lf**
Closes #22 

Finally made it work with the GPU also. Only had to change the base image to an official one from NVIDIA (which also supports cuDNN 8).

I added a description on how to set it up for a different worker and run it on the wiki of the example worker and pointed to the wiki in the README.

### CODE REVIEW

**Review by Veldhoen — COMMENTED** [review]
I was having issues downloading the model from huggingface, download timed out for the bigger models. But you already created a separate issue for that. 
Worker still runs fine with CPU on my local machine!
I wanted to test in the GPU server, but it turns out we can't access it anymore. I plan to test it in Openshift, but I'm gonna need some help for that so it will have to wait until next week.

**Comment by Veldhoen** [comment]
Not really related to GPU-containerization, but maybe add config.yml to .dockerignore, to make sure that the worker is using the config mounted in /root/.DANE

**Comment by greenw0lf** [comment]
It already is there (`/config`)

**Comment by greenw0lf** [comment]
Shall I merge?

**Comment by greenw0lf** [comment]
@Veldhoen reminder that I left some comments. Shall I go ahead and merge?

**Comment by Veldhoen** [comment]
Sorry for the late reply - yes go ahead!

**Pull request merged**
